os:
  - osx

language: objective-c


before_install:
  - brew update


script:
  - ansible-playbook -i hosts -K main.yml --syntax-check
  - ansible-playbook main.yml -i hosts -connection=local --sudo -vv


notifications:
  email: false
