os:
  - osx

language: python
python: "2.7"

before_install:
  - brew update


script:
  - ansible-playbook -i hosts -K main.yml --syntax-check
  - ansible-playbook main.yml -i hosts -connection=local --sudo -vv

