---

- hosts: all
  gather_facts: true

  vars:
    user:
        # Change these before continuing
        id: tylerhardy
        name: Tyler Hardy
        nickname: tyler
        email: tylerhardy@gmail.com

  tasks:
     # - include: tasks/brew.yml
     - include: tasks/python.yml
     - include: tasks/sublime.yml
     - include: tasks/git.yml
     - include: tasks/iterm2.yml
     - include: tasks/dot.yml
     - include: tasks/scripts.yml
