---
- hosts: localhost

  vars_files:
    - vars/main.yml

  tasks:

    - name: Install Cask Applications
      homebrew_cask: name={{item}} state=installed
      with_items: homebrew.cask.apps

    - name: Install packages with homebrew
      homebrew: name={{item}} state=present
      with_items: homebrew.packages

    - name: Install pip packages
      pip: name={{item}}
      with_items: pip.packages

    - name: Install Source Code Pro
      git: repo={{item}} dest={{source_code_pro.dest_folder}} clone=yes version=1.017R accept_hostkey=yes
      with_items: source_code_pro.repo


    - name: Setup OSX Defaults
      command: sh files/osx.sh

    # - name: Create Symlinks


    - name: Install NPM Pakacges
      npm: name={{ item }} global=yes state=present
      with_items: npm.packages


    # - name: Install Vagrant with Default Phusion Box



    # - name: Install custom SublimeText Themes
    #   git: >
    #     repo={{item.repo}}
    #     dest="/Users/{{user}}/Library/Application Support/Sublime Text/Packages/Theme - {{item.name}}"
    #     accept_hostkey=yess
    #   with_items: sublime_text.themes
    #   ignore_errors: yes




    - name: Register Git user
      command: >
        git config --global user.name "{{git.global.user_name}}"

    - name: Register Git email
      command: >
        git config --global user.email "{{git.global.user_email}}"



