---

- hosts: all
  gather_facts: true

  vars:
    user:
        id: tylerhardy
        name: Tyler Hardy
        nickname: tyler
        email: tylerhardy@gmail.com

  tasks:
     - include: tasks/brew.yml
     - include: tasks/python.yml
     - include: tasks/sublime.yml
     - include: tasks/git.yml
    # # Last Because Configration After Everything Installs
    # # Also Need to Find A Better Place to Put It
     - include: tasks/dot.yml
    # Personalization Scripts (Need to make it better right now is c & p)
     - include: tasks/scripts.yml

