---

- name: Brew Tap
  homebrew_tap:
    tap: "{{ item }}"
    state: present
  with_items:
    - caskroom/fonts
    - homebrew/completions
    - caskroom/versions

- name: Install packages with homebrew
  homebrew: name={{item}} state=present
  with_items:
      - git
      - go
      - ssh-copy-id
      - wget
      - tree
      - ansible
      - python
      - python3
      - hugo

- name: Upgrade Brew Packages
  homebrew: upgrade_all=yes


- name: Install Cask Applications
  homebrew_cask: name={{item}} state=installed
  ignore_errors: true
  with_items:
      - sublime-text
      - virtualbox
      - visual-studio-code
      - vlc
      - dropbox
      - google-drive
      - iterm2
      - the-unarchiver
      - flux
      - transmission
      - keepingyouawake
      - google-chrome
      - firefoxdeveloperedition
      - font-awesome-terminal-fonts
      - font-source-code-pro
      - dash
      - sourcetree


# Homebrew Vars
