---

- name: Copy Git Config
  template:
    src: files/dot/gitconfig
    dest: "/Users/{{user.id }}/.gitconfig"
    mode: 0644
    owner: "{{ user.id }}"
    group: staff

- name: Register Git user
  command: >
      git config --global user.name "@{{ user.id }}"
  changed_when: false

- name: Register Git email
  command: >
       git config --global user.email "{{ user.email }}"
  changed_when: false
