export PS1="\[\e[00;33m\]\u\[\e[0m\]\[\e[00;37m\]@\h:\n\[\e[0m\]\[\e[00;36m\][\w]:\[\e[0m\]\[\e[00;37m\] \[\e[0m\]"
export CLICOLOR=1
export LSCOLORS=ExFxCxDxBxegedabagacad

export ANDROID_HOME=/Users/shapath/Developer/SDK/AndroidSDK
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/platform-tools

export PATH="/Applications/Postgres.app/Contents/Versions/9.3/bin:$PATH"
export PATH="/Applications/Postgres.app/Contents/Versions/9.3/bin:$PATH"



export DEV="local"
export DEBUG="true"
#Env Variables

    #Production Key
export DEBUG_SECRET_KEY="cATx~{@==@wT%hUr=0:^V-YRM_a<4WJ#zv,l:;q|ezFcSiUefC"




#Open Files
alias e="sl ~/.bash_profile"
alias save="source ~/.bash_profile"

#Open Programs
alias studio="open /Applications/Android\ Studio.app"

#Directories
alias ws="cd /Users/shapath/Developer"
alias dws="cd /Users/shapath/Developer/django"
alias aws="cd /Users/shapath/Developer/android"



#Python
alias ve="source bin/activate"
alias d="deactivate"
alias pf="pip freeze > requirements.txt"
export PIP_DEFAULT_TIMEOUT=60


#Django

alias rs="python manage.py runserver 0.0.0.0:8000"
alias sdb="python manage.py syncdb"
alias mm="python manage.py makemigrations"
alias m="python manage.py migrate"

    #Python Projects

alias muvi="dws; cd muvi; ve; cd Showtime"
alias partify="dws; cd partify;ve; cd partify"
alias cinetime="dws; cd cinetime;ve; cd cinetime"
alias chup="dws; cd chupchap; ve; cd chupchap"
alias push="dws; cd push; ve; cd app"


#Android
alias debug="adb connect 10.10.0.36:5555"
alias wconnect="adb forward tcp:4444 localabstract:/adb-hub; adb connect localhost:4444"

#Git
alias gs='git status '
alias ga='git add '
alias gb='git branch '
alias gc='git commit'
alias gd='git diff'
alias gco='git checkout '
alias gk='gitk --all&'
alias gx='gitx --all'

alias gac="git add -A && git commit -m"

alias got='git '
alias get='git '

#Network
alias ip='ipconfig getifaddr en0'
alias spoofmac="spoof-mac.py randomize wi-fi"


#Vagrant Default Instance
alias vup="vagrant up 6276f2d"
alias vreload="vagrant reload 6276f2d"
alias vhalt="vagrant halt 6276f2d"
alias vssh="vagrant ssh 6276f2d"
alias vstart="vup; vssh"


### SSH
alias sshcinetime="ssh -p 2063 shapath@128.199.124.199"
alias pub="cat ~/.ssh/id_rsa.pub"


#Bash Functions


transfer() {
    # check arguments
    if [ $# -eq 0 ];
    then
        echo "No arguments specified. Usage:\necho transfer /tmp/test.md\ncat /tmp/test.md | transfer test.md"
        return 1
    fi

    # get temporarily filename, output is written to this file show progress can be showed
    tmpfile=$( mktemp -t transferXXX )

    # upload stdin or file
    file=$1

    if tty -s;
    then
        basefile=$(basename "$file" | sed -e 's/[^a-zA-Z0-9._-]/-/g')

        if [ ! -e $file ];
        then
            echo "File $file doesn't exists."
            return 1
        fi

        if [ -d $file ];
        then
            # zip directory and transfer
            zipfile=$( mktemp -t transferXXX.zip )
            cd $(dirname $file) && zip -r -q - $(basename $file) >> $zipfile
            curl --progress-bar --upload-file "$zipfile" "https://transfer.sh/$basefile.zip" >> $tmpfile
            rm -f $zipfile
        else
            # transfer file
            curl --progress-bar --upload-file "$file" "https://transfer.sh/$basefile" >> $tmpfile
        fi
    else
        # transfer pipe
        curl --progress-bar --upload-file "-" "https://transfer.sh/$file" >> $tmpfile
    fi

    # cat output link
    cat $tmpfile

    # cleanup
    rm -f $tmpfile
}

alias transfer=transfer
