###########################################
## Put Enviornment Varibals in .bash_env ##
###########################################
export PS1="\[\e[00;33m\]\u\[\e[0m\]\[\e[00;37m\]@\h:\n\[\e[0m\]\[\e[00;36m\][\w]:\[\e[0m\]\[\e[00;37m\] \[\e[0m\]"

export GOPATH=$HOME/Developer/SDK/godir
export PATH=$PATH:$GOPATH/bin

export ANDROID_HOME=/Users/shapath/Developer/SDK/AndroidSDK

export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/platform-tools

export EDITOR=nano

#Env Variables

    #Production Key

    #Database Keys

alias g="git "
source `brew --prefix git`/etc/bash_completion.d/git-completion.bash
complete -o default -o nospace -F _git g


#Brew Overrides All System Apps
alias f="foundation-apps "

#Open Files
alias e="sl ~/.bash_profile"
alias save="source ~/.bash_profile"

alias blog="ws; cd www; cd blog"


#Open Programs
alias studio="open ~/Applications/Android\ Studio.app"

#Directories
alias ws="cd /Users/shapath/Developer"
alias dws="cd /Users/shapath/Developer/django"
alias aws="cd /Users/shapath/Developer/Android"


#Provision
alias provision="sl /Users/shapath/Developer/provision/mac_dev_provision"
alias build="cd /Users/shapath/Developer/provision/mac_dev_provision; make -f Makefile"

#Python
alias ve="source bin/activate"
alias d="deactivate"
alias req="pip freeze > requirements.txt"
export PIP_DEFAULT_TIMEOUT=60

alias pyfmt="find . -name '*.py' -exec autopep8 --in-place --jobs=1 '{}' \;"
#Django

alias rs="python manage.py runserver 0.0.0.0:8000"
alias sdb="python manage.py syncdb"
alias mm="python manage.py makemigrations"
alias m="python manage.py migrate"

    #Python Projects

alias si="dws;cd siddhamahayoga; ve; cd app; clear"
alias ne="dws;cd neptiun; ve; cd app; clear"
alias sk="dws;cd skyshot; ve; cd app; clear"


#Android
alias debug="adb connect 10.10.0.36:5555"
alias wconnect="adb forward tcp:4444 localabstract:/adb-hub; adb connect localhost:4444"


#Network
alias ip='ipconfig getifaddr en0'


export VAGRANT_ID="7d01fab"

#Vagrant Default Instance
alias vup="vagrant up $VAGRANT_ID"
alias vreload="vagrant reload $VAGRANT_ID"
alias vhalt="vagrant halt $VAGRANT_ID"
alias vssh="vagrant ssh $VAGRANT_ID"
alias vprov="sl /Users/shapath/Developer/vagrant/box"
alias vbuild="vagrant provision $VAGRANT_ID"
alias vsuspend="vagrant suspend $VAGRANT_ID"
alias vstart="vup; vssh"
alias vrestart="vhalt; vstart"

if [ -f `brew --prefix`/etc/bash_completion.d/vagrant ]; then
    source `brew --prefix`/etc/bash_completion.d/vagrant
fi

if [ -f `brew --prefix`/etc/bash_completion.d/django ]; then
    source `brew --prefix`/etc/bash_completion.d/django
fi

if [ -f `brew --prefix`/etc/bash_completion.d/pip ]; then
    source `brew --prefix`/etc/bash_completion.d/pip
fi

### Added by the Heroku Toolbelt

### SSH
# alias sshcinetime="ssh -p 2063 shapath@128.199.124.199"
alias pub="cat ~/.ssh/id_rsa.pub | pbcopy"


#Bash Functions




transfer() {
    # check arguments
    if [ $# -eq 0 ];
    then
        echo "No arguments specified. Usage:\necho transfer /tmp/test.md\ncat /tmp/test.md | transfer test.md"
        return 1
    fi

    # get temporarily filename, output is written to this file show progress can be showed
    tmpfile=$( mktemp -t transferXXX )

    # upload stdin or file
    file=$1

    if tty -s;
    then
        basefile=$(basename "$file" | sed -e 's/[^a-zA-Z0-9._-]/-/g')

        if [ ! -e $file ];
        then
            echo "File $file doesn't exists."
            return 1
        fi

        if [ -d $file ];
        then
            # zip directory and transfer
            zipfile=$( mktemp -t transferXXX.zip )
            cd $(dirname $file) && zip -r -q - $(basename $file) >> $zipfile
            curl --progress-bar --upload-file "$zipfile" "https://transfer.sh/$basefile.zip" >> $tmpfile
            rm -f $zipfile
        else
            # transfer file
            curl --progress-bar --upload-file "$file" "https://transfer.sh/$basefile" >> $tmpfile
        fi
    else
        # transfer pipe
        curl --progress-bar --upload-file "-" "https://transfer.sh/$file" >> $tmpfile
    fi

    # cat output link
    cat $tmpfile

    # cleanup
    rm -f $tmpfile
}

alias transfer=transfer


if [ -f ~/.bash_env ]; then
    . ~/.bash_env
fi
