###########################################
## Put Enviornment Varibals in .bash_env ##
###########################################


export PS1="\[\e[00;33m\]\u\[\e[0m\]\[\e[00;37m\]@\h:\n\[\e[0m\]\[\e[00;36m\][\w]:\[\e[0m\]\[\e[00;37m\] \[\e[0m\]"



export ANDROID_HOME=/Users/shapath/Developer/SDK/AndroidSDK
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/platform-tools


export DEV="local"
export DEBUG="true"
#Env Variables

    #Production Key

    #Database Keys


#Brew Overrides All System Apps

#Open Files
alias e="sl ~/.bash_profile"
alias save="source ~/.bash_profile"

#Open Programs
alias studio="open ~/Applications/Android\ Studio.app"

#Directories
alias ws="cd /Users/shapath/Developer"
alias dws="cd /Users/shapath/Developer/django"
alias aws="cd /Users/shapath/Developer/Android"


#Provision
alias provision="sl /Users/shapath/Developer/provision/mac_dev_provision"
alias build="cd /Users/shapath/Developer/provision/mac_dev_provision; make -f Makefile"

#Python
alias ve="source bin/activate"
alias d="deactivate"
alias req="pip freeze > requirements.txt"
export PIP_DEFAULT_TIMEOUT=60


#Django

alias rs="python manage.py runserver 0.0.0.0:8000"
alias sdb="python manage.py syncdb"
alias mm="python manage.py makemigrations"
alias m="python manage.py migrate"

    #Python Projects

alias traq="dws;cd traq; ve; cd app; clear"

#Android
alias debug="adb connect 10.10.0.36:5555"
alias wconnect="adb forward tcp:4444 localabstract:/adb-hub; adb connect localhost:4444"

#Git
alias gs='git status '
alias ga='git add '
alias gb='git branch '
alias gc='git commit'
alias gd='git diff'
alias gco='git checkout '
alias gk='gitk --all&'
alias gx='gitx --all'

alias gac="git add -A && git commit -m"

alias got='git '
alias get='git '

#Network
alias ip='ipconfig getifaddr en0'


export VAGRANT_ID="b5a2e49"

#Vagrant Default Instance
alias vup="vagrant up $VAGRANT_ID"
alias vreload="vagrant reload $VAGRANT_ID"
alias vhalt="vagrant halt $VAGRANT_ID"
alias vssh="vagrant ssh $VAGRANT_ID"
alias vprov="vagrant provision $VAGRANT_ID"
alias vstart="vup; vssh"
alias vrestart="vhalt; vstart"

### Added by the Heroku Toolbelt

### SSH
# alias sshcinetime="ssh -p 2063 shapath@128.199.124.199"
alias pub="cat ~/.ssh/id_rsa.pub | pbcopy"


#Bash Functions




transfer() {
    # check arguments
    if [ $# -eq 0 ];
    then
        echo "No arguments specified. Usage:\necho transfer /tmp/test.md\ncat /tmp/test.md | transfer test.md"
        return 1
    fi

    # get temporarily filename, output is written to this file show progress can be showed
    tmpfile=$( mktemp -t transferXXX )

    # upload stdin or file
    file=$1

    if tty -s;
    then
        basefile=$(basename "$file" | sed -e 's/[^a-zA-Z0-9._-]/-/g')

        if [ ! -e $file ];
        then
            echo "File $file doesn't exists."
            return 1
        fi

        if [ -d $file ];
        then
            # zip directory and transfer
            zipfile=$( mktemp -t transferXXX.zip )
            cd $(dirname $file) && zip -r -q - $(basename $file) >> $zipfile
            curl --progress-bar --upload-file "$zipfile" "https://transfer.sh/$basefile.zip" >> $tmpfile
            rm -f $zipfile
        else
            # transfer file
            curl --progress-bar --upload-file "$file" "https://transfer.sh/$basefile" >> $tmpfile
        fi
    else
        # transfer pipe
        curl --progress-bar --upload-file "-" "https://transfer.sh/$file" >> $tmpfile
    fi

    # cat output link
    cat $tmpfile

    # cleanup
    rm -f $tmpfile
}

alias transfer=transfer


if [ -f ~/.bash_env ]; then
    . ~/.bash_env
fi
